### ISSUE TITLE
Supporing Custom Aggrigations

### ISSUE THREAD

**Issue by AliMahmodi** [ffernandolima/mongo-db-data-access#14]
Great work , but I did not realize how to use AGGRIGATION .

Thanks

**Comment by ffernandolima** [comment]
Hi @AliMahmodi!

For complex query operators like aggregations, a custom repository should be used instead.

There's an example [here](https://github.com/ffernandolima/mongo-db-data-access/blob/eb95b7d695bebe3326b477740de14cdd9f8c752f/samples/MongoDB.Data/Repositories/CustomBlogRepository.cs#L11) demonstrating how to create a custom repository and use all available features from `IMongoQueryable`.

The custom repository can be instantiated through `IMongoDbUnitOfWork` which inherits from `IMongoDbRepositoryFactory`, by accessing CustomRepository available method.

Example:

```
// Example: Custom Repository

var repository = _unitOfWork.CustomRepository<ICustomBlogRepository>();

var urls = repository.GetAllBlogUrls();
```

**Comment by ffernandolima** [comment]
Closing this issue for now. In case you need further assistance, please let me know.
