### ISSUE TITLE
How to have a custom collection name for repositories using Unit of Work?

### ISSUE THREAD

**Issue by bhbghghbgb** [ffernandolima/mongo-db-data-access#16]
Hello, I am learning ASP.NET with MongoDB and Unit of Work pattern with your library.

I can't figure out how to have a custom collection name when using unit of work.

The unit of work is injected into the service like so

```cs
public class FooBarService(
    IMongoDbUnitOfWork<BloggingContext> unitOfWork
)
{
    private readonly IMongoDbUnitOfWork<BloggingContext> _unitOfWork = unitOfWork;
}
```

When using these methods, I can't find a way to set a custom collection name:

```cs
var fooRepository = _unitOfWork.CustomRepository<IFooRepository>();
var fooRepository2 = _unitOfWork.Repository<Foo>();
```

In `IMongoDbSyncContext.cs`, the interface `IMongoDbSyncContext` one of the `GetCollection<T>` overload method allows a custom collection name:

```cs
IMongoCollection<T> GetCollection<T>(MongoCollectionSettings settings = null);
IMongoCollection<T> GetCollection<T>(string name, MongoCollectionSettings settings = null);
```

But in `MongoDbRepository.cs`, the class `MongoDbRepository<T>` has only one constructor and it creates a readonly Collection without a name:

```cs
protected IMongoDbContext Context { get; }

protected IMongoCollection<T> Collection { get; }

public MongoDbRepository(IMongoDbContext context)
{
    Context = context ?? throw new ArgumentNullException("context", "context cannot be null.");
    Collection = context.GetCollection<T>();
}
```

Knowing that the interface `IMongoDbSyncContext` has a `GetCollection<T>` overload method that allows a custom collection name, I can use the `appsettings.json` config file to configure the collection names based on the Model class name:

```cs
public class CrudRepository<T> : MongoDbRepository<T>, ICrudRepository<T>
{
    protected readonly IMongoCollection<T> _collection;

    public CrudRepository(
        BloggingContext context,
        IOptions<MongoDbSettings> mongoDbSettings,
    )
        : base(context)
    {
        _collection = Context.GetCollection<T>(
            mongoDbSettings.Value.CollectionNames[typeof(T).Name]
        );
    }
```

However, operations on `_collection` do not go through the unit of work, so every operations on it is saved immediately even if `_unitOfWork.SaveChanges()` has not been called.

**Comment by ffernandolima** [comment]
Hi @bhbghghbgb!

I've just addressed it through this [PR](https://github.com/ffernandolima/mongo-db-data-access/pull/17).

Now while registering a repository you can specify an options class instance with a custom collection name like this:

```C#

services.AddCustomMongoDbRepository<ICustomBlogRepository, CustomBlogRepository>(
    provider => 
        new CustomBlogRepository(
            provider.GetService<BloggingContext>(),
            new MongoDbRepositoryOptions<Blog> { CollectionName = "Blog" }));        
```
The same applies to the `AddMongoDbRepository` extension.

I hope I helped you.

**Comment by ffernandolima** [comment]
Closing this issue for now.
